apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hw-registry.fullname" . }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    {{- include "hw-registry.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "hw-registry.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hw-registry.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
    {{- end }}
      serviceAccountName: {{ include "hw-registry.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
           - name: DB_NAME
             valueFrom:
               secretKeyRef:
                  name: {{ include "hw-registry.name" . }}
                  key: sql_db
           - name: DB_USER
             valueFrom:
               secretKeyRef:
                  name: {{ include "hw-registry.name" . }}
                  key: sql_user
           - name: DB_PASSWORD
             valueFrom:
                secretKeyRef:
                   name: {{ include "hw-registry.name" . }}
                   key: sql_password
           - name: DB_PORT
             valueFrom:
                secretKeyRef:
                   name: {{ include "hw-registry.name" . }}
                   key: sql_port
           - name: DB_HOST
             valueFrom:
                secretKeyRef:
                   name: {{ include "hw-registry.name" . }}
                   key: sql_host
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
      restartPolicy: {{ .Values.restartPolicy }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
