apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hw-registry.name" . }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    {{- include "hw-registry.labels" . | nindent 4 }}
data:
  {{- if .Values.environment.sql_db }}
  sql_db: {{ .Values.environment.sql_db | b64enc | quote }}
  {{- end }}
  {{- if .Values.environment.sql_host }}
  sql_host: {{ .Values.environment.sql_host | b64enc | quote }}
  {{- end }}
  {{- if .Values.environment.sql_password }}
  sql_password: {{ .Values.environment.sql_password | b64enc | quote }}
  {{- end }}
  {{- if .Values.environment.sql_user }}
  sql_user: {{ .Values.environment.sql_user | b64enc | quote }}
  {{- end }}
  {{- if .Values.environment.sql_port }}
  sql_port: {{ .Values.environment.sql_port | b64enc | quote }}
  {{- end }}
